# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM node:lts-alpine
WORKDIR /app

# Install dependencies and build
COPY package.json package-lock.json tsconfig.json ./
COPY src ./src
RUN npm install && npm run build

# Trim dev deps
RUN npm prune --production

# Use direct node invocation to run server over stdio
ENTRYPOINT ["node", "dist/index.js"]
